baseURL = ""
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"
title = "Lynx"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params.author]
   name = "Fluffy Paws"
   headline = "Cat are awesome, you can write your description about your store or yourself here"
   image = "img/author.jpg"  # path relative to static directory
   
links = [
     { link = { href = "/styles", text = "Link lainnya" } },
     { grabfood = { href = "", text = "GrabFood" } },
     { shopeefood = { href = "", text = "ShopeeFood" } },
     { gofood = { href = "", text = "GoFood" } },
     { shopee = { href = "", text = "Shopee" } },
     { lazada = { href = "", text = "Lazada" } },
     { tokopedia = { href = "", text = "Tokopedia" } },
     { map = { href = "", text = "Lokasi", icon = "pin-drop"} },
     { facebook = "" },
     { instagram = "" },
     { linkedin = "" },
     { telegram = "" },
     { tiktok = "" },
     { whatsapp = "" },
     { x = "" },
     { youtube = "" }
  ]
  
  
 

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
