baseURL = ""
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"
title = "Lynx"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]
  
[params.author]
   name = "Your name here"
   headline = "An awesome person and your amazing, just the way you are, anjay"
   image = "img/author.jpg"  # path relative to static directory
   
links = [
     { facebook = "https://facebook.com/username" },
     { instagram = "https://instagram.com/username" },
     { linkedin = "https://linkedin.com/in/username" },
     { pinterest = "https://pinterest.com/username" },
     { soundcloud = "https://soundcloud.com/username" },
     { spotify = "https://spotify.com/user/username" },
     { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/username" },
     { threads = "https://threads.com/username" },
     { tiktok = "https://tiktok.com/@username" },
     { whatsapp = "https://wa.me/phone-number" },
     { x = "https://x.com/username" },
     { youtube = "https://youtube.com/username" },
  ]
  
  
 

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
